<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="Google.Apis.Books.v1" Version="1.68.0.3331" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="8.10.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GoogleBooks.Application\GoogleBooks.Application.csproj" />
    <ProjectReference Include="..\GoogleBooks.Domain\GoogleBooks.Domain.csproj" />
  </ItemGroup>

</Project>
