<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Books\GetBookByIdIntegrationTests\ExpectedGetBookByIdContent.json" />
    <None Remove="Books\GetBookByIdIntegrationTests\ExpectedServiceUnavailableContent.json" />
    <None Remove="Books\GetBookByIdIntegrationTests\MockedGoogleBooksServiceUnavailableContent.json" />
    <None Remove="Books\ListBooksByKeyWordsIntegrationTests\Should\ExpectedListBooksByKeyWordsResult.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Books\GetBookByIdIntegrationTests\ExpectedExternalServerErrorResult.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="ExpectedInternalServerErrorResult.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Books\GetBookByIdIntegrationTests\Should\ExpectedGetBookByIdContent.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Books\GetBookByIdIntegrationTests\ServiceUnavailable\ExpectedServiceUnavailableContent.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Books\GetBookByIdIntegrationTests\Should\MockedGetBookByIdResponse.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Books\GetBookByIdIntegrationTests\ServiceUnavailable\MockedUnavailableContent.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Books\ListBooksByKeyWordsIntegrationTests\Should\ExpectedListBooksByKeyWordsResult.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Books\ListBooksByKeyWordsIntegrationTests\Should\MockedListBooksByKeyWordsResponse.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Readers\GetReaderByIdIntegrationTests\ExpectedNotFoundErrorResult.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="35.6.5" />
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.20" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Testcontainers.MongoDb" Version="4.7.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" Version="3.1.0" />
    <PackageReference Include="xunit.v3.assert" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\GoogleBooks.WebApi\GoogleBooks.WebApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
